fishing:
  fishing-tables:
    basic:
      RED_MUSHROOM: 0.1, 1, 1
      COAL: 0.89, 1, 2
      DIAMOND_BLOCK: 0.01, 1, 1
    treasure:
      DIAMOND_BLOCK: 0.4, 5, 5
      GOLD: 0.5, 8, 16
      NETHERITE_SCRAP: 0.1, 1, 1
basic:
  HERE: taco
  THERE: not taco