name: BetterFishing
version: '${project.version}'
main: org.layanegg.betterfishing.BetterFishing
api-version: '1.20'
commands:
  rod:
    description: An easy way to get a fishing rod!
    usage: /<command>
    aliases: fishingrod
  feed:
    description: Satiate your hunger
    usage: /<command>
    aliases: [food, yum]